- name: make backup
  copy:
    src: /etc/zabbix/zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf_backup
    remote_src: yes
    force: no

- name: replace config for "Server"
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Server=127.0.0.1$'
    replace: 'Server=52.192.182.98'

- name: replace config for "Hostname"
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Hostname=Zabbix\sserver$'
    replace: 'Hostname=psqltest12'
