- name: copy zabbix-agent.conf
  vars:
    now_date: "{{ lookup('pipe','date +%Y%m%d') }}"
  copy:
    src: /etc/zabbix/zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf_{{ now_date }}
    remote_src: yes
    force: no

- name: copy zabbix-proxy.conf
  vars:
    now_date: "{{ lookup('pipe','date +%Y%m%d%H%M') }}"
  copy:
    src: /etc/zabbix/zabbix_proxy.conf
    dest: /etc/zabbix/zabbix_proxy.conf_{{ now_date }}
    remote_src: yes
    force: no

- name: stop zabbix-agent
  systemd:
    name: zabbix-agent
    state: stopped

- name: stop zabbix-proxy
  systemd:
    name: zabbix-proxy
    state: stopped

- name: remove zabbix-proxy, zabbix-agent
  yum:
    name: zabbix-proxy
    state: removed

- name: install zabbix-4.0.21 repository
  yum:
    name: http://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
    state: latest

- name: yum clean all
  shell: yum clean all

- name: install zabbix-proxy-sqlite3, zabbi-agent
  yum:
    name: zabbix-proxy-sqlite3
    state: latest

- name: create sqlite3 dir
  file:
    path: /var/lib/sqlite3
    state: directory
    owner: zabbix
    group: zabbix
    mode: 0755

- name: confirm zabbix.db
  stat:
    path: /var/lib/sqlite3/zabbix.db
  register: result_zabbixdb

- name: deploy db data
  #shell: zcat /usr/share/doc/zabbix-proxy-sqlite3-4.0.21/schema.sql.gz | /bin/sqlite3 zabbix.db
  shell: zcat /usr/share/doc/zabbix-proxy-sqlite3-*/schema.sql.gz | /bin/sqlite3 zabbix.db
    chdir=/var/lib/sqlite3/
  when: not result_zabbixdb.stat.exists

- name: chown zabbix.db
  shell: chown zabbix:zabbix zabbix.db
    chdir=/var/lib/sqlite3/

- name: zabbix-proxy.conf change
  lineinfile:
    dest: "/etc/zabbix/zabbix_proxy.conf"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "Server=127.0.0.1" ,line: "Server=52.192.182.98" }
    - { regexp: "DBName=zabbix_proxy" ,line: "DBName=/var/lib/sqlite3/zabbix.db" }
    - { regexp: "Hostname=Zabbix proxy" ,line:  "Hostname={{ inventory_hostname }}" }
    - { regexp: "Timeout=4" ,line:  "Timeout=30" }

- name: zabbix-agent.conf change
  lineinfile:
    dest: "/etc/zabbix/zabbix_agentd.conf"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "Server=127.0.0.1" ,line: "Server=172.31.12.73" }
    - { regexp: "Hostname=Zabbix proxy" ,line:  "Hostname={{ inventory_hostname }}" }
    - { regexp: "Timeout=4" ,line:  "Timeout=30" }

- name: start zabbix-proxy
  systemd:
    name: zabbix-proxy
    state: started

- name: start zabbix-agent
  systemd:
    name: zabbix-agent
    state: started









